In [44]:
import numpy as np
from scipy import linalg

In [57]:
B = np.random.rand(3,3)
C = np.random.rand(3,3,2)

In [46]:

k=2
n_k = np.array([0, 1, 2, 3.])
np.exp(1j*(k-1)*n_k[1:])
coef = np.array([1, 10, 100])

In [47]:
res = C * coef

In [48]:
res[:,:,0] - C[:,:,0]*1

array([[0., 0.],
       [0., 0.]])

In [49]:
res[:,:,1]- C[:,:,1]*10

array([[0., 0.],
       [0., 0.]])

In [50]:
res[:,:,2] - C[:,:,2]*100

array([[0., 0.],
       [0., 0.]])

In [51]:
np.sum(res, axis=2) - C[:,:,0]*1 - C[:,:,1]*10 - C[:,:,2]*100

array([[1.42108547e-14, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00]])

In [52]:
# test case
basic_delay = 0.5
E = np.array([[1,0,0], [0,1,0], [0,0,0]], dtype=np.float64)
C = np.array([[[0.4143223486277966, 0.40201266779316314, 0.9226682386225298],
  [0.5879222085099505, 0.7080664294805299, 0.13572413035312103]],
 [[0.030809383167185955, 0.5002637311809033, 0.6322297634469464],
  [0.14666972360755948, 0.968129694154458, 0.06643651756158409]]], dtype=np.float64)
tau = np.array([0, 0.5, 1.0, 1.5])
             

In [58]:
B.tolist()

[[0.3116072141901096, 0.40602145612523965, 0.6776544796580569],
 [0.11363668625750645, 0.9343699659543538, 0.6977236310729171],
 [0.2941822873723423, 0.4997871977470306, 0.6949324821183755]]

In [59]:
C.tolist()

[[[0.7622980349226127, 0.22478751290330823],
  [0.48683084185446224, 0.8488352460039917],
  [0.32647364799957856, 0.02564225148608379]],
 [[0.3306919345179705, 0.4461952281462491],
  [0.5706006218521886, 0.17014364199309917],
  [0.4775272358483136, 0.9953991667479567]],
 [[0.44686477247542555, 0.17775612836209154],
  [0.008192538279984674, 0.5716834321644337],
  [0.6357900350689626, 0.03723974619198067]]]

In [55]:
C[0]

array([[0.41432235, 0.40201267, 0.92266824],
       [0.58792221, 0.70806643, 0.13572413]])