# Jupyter-notebook for testing operations (mainly for comparison)

In [1]:
import numpy as np

In [2]:
# Typical representation
A0 = np.array([[-1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, -10, -4],
               [0, 0, 4, -10]])
A1 = np.array([[3, 3, 3, 3],
               [0, -1.5, 0, 0],
               [0, 0, 3, -5],
               [0, 5, 5, 5]])
A=[A0, A1]
hA=[0, 1.]

In [3]:
np.stack([A0[:,:,np.newaxis], A], axis=2)

ValueError: all input arrays must have the same shape

In [ ]:
# Comparison
A = np.stack([A0, A1, A1*10], axis=2) # (n_states, n_states, n_delays)
hA = hA=np.array([0, 1., 2, 3])

In [4]:
np.concatenate([A0[:,:,np.newaxis], A], axis=2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [59]:
DD = np.random.rand(3,3,4)
hDD = np.array([0.3, 0.46, 0.48, 1.5])
u = np.random.rand(3,) + 1j*np.random.rand(3,)
v = np.random.rand(3,) + 1j*np.random.rand(3,)

In [60]:
# one shot


In [61]:
DD.shape

(3, 3, 4)

In [62]:
np.conj(u[np.newaxis, ]) @ DD[:,:,0]

array([[0.35420586-0.10532599j, 0.88901118-0.61335586j,
        0.73177854-0.37038361j]])

In [72]:
np.ravel()

array([[3.87102726+1.12420229j]])

In [64]:
pom = np.conj(u[np.newaxis, np.newaxis, ]) @ np.transpose(DD, (1,0,2))
pom

array([[[0.35420586-0.10532599j, 0.99196665-0.5031648j ,
         1.18214463-0.75940259j, 1.31047856-0.63000362j]],

       [[0.88901118-0.61335586j, 1.61633642-0.72388863j,
         0.88541662-0.57948834j, 1.06701478-0.38574745j]],

       [[0.73177854-0.37038361j, 0.73973774-0.48182061j,
         1.50150753-0.75744051j, 0.87277868-0.51356456j]]])

In [65]:
pom.shape

(3, 1, 4)

In [66]:
r = v[np.newaxis, :] @ np.transpose(pom, (1,0,2)) 

In [67]:
np.ravel(r).shape

(4,)

In [68]:
np.ravel(r)

array([1.93551363+0.56210115j, 3.41212929+1.17027306j,
       3.3489107 +1.3697247j , 3.01398257+1.45968292j])

In [69]:
np.conj(u[np.newaxis, ]) @ np.transpose(v[np.newaxis, :] @ DD, (1,0,2))

array([[[1.93551363+0.56210115j, 3.41212929+1.17027306j,
         3.3489107 +1.3697247j , 3.01398257+1.45968292j]]])