# Jupyter-notebook for testing operations (mainly for comparison)

In [2]:
import numpy as np

In [3]:
# Typical representation
A0 = np.array([[-1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, -10, -4],
               [0, 0, 4, -10]])
A1 = np.array([[3, 3, 3, 3],
               [0, -1.5, 0, 0],
               [0, 0, 3, -5],
               [0, 5, 5, 5]])
A=[A0, A1]
hA=[0, 1.]

In [26]:
# Comparison
A = np.stack([A0, A1, A1*10, A1*100], axis=2) # (n_states, n_states, n_delays)
hA = hA=np.array([0, 1., 2, 3])

In [27]:
A.shape

(4, 4, 4)

In [28]:
res = (A * np.exp(hA))

In [29]:
res[:,:,0]

array([[ -1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0., -10.,  -4.],
       [  0.,   0.,   4., -10.]])

In [30]:
res[:,:,1]

array([[  8.15484549,   8.15484549,   8.15484549,   8.15484549],
       [  0.        ,  -4.07742274,   0.        ,   0.        ],
       [  0.        ,   0.        ,   8.15484549, -13.59140914],
       [  0.        ,  13.59140914,  13.59140914,  13.59140914]])

In [31]:
res[:,:,2]

array([[ 221.67168297,  221.67168297,  221.67168297,  221.67168297],
       [   0.        , -110.83584148,    0.        ,    0.        ],
       [   0.        ,    0.        ,  221.67168297, -369.45280495],
       [   0.        ,  369.45280495,  369.45280495,  369.45280495]])

In [32]:
res[:,:,3]

array([[  6025.66107696,   6025.66107696,   6025.66107696,
          6025.66107696],
       [     0.        ,  -3012.83053848,      0.        ,
             0.        ],
       [     0.        ,      0.        ,   6025.66107696,
        -10042.76846159],
       [     0.        ,  10042.76846159,  10042.76846159,
         10042.76846159]])