# Jupyter-notebook for testing operations (mainly for comparison)

In [1]:
import numpy as np
from scipy import linalg

In [2]:
# Typical representation
A0 = np.array([[-1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, -10, -4],
               [0, 0, 4, -10]])
A1 = np.array([[3, 3, 3, 3],
               [0, -1.5, 0, 0],
               [0, 0, 3, -5],
               [0, 5, 5, 5]])
A=np.stack([A0, A1], axis=2)
hA=np.array([0, 1.])
E = np.eye(4)

In [3]:
# perform tests
complex_vector = np.random.rand(10) + np.random.rand(10)*1j

for z in complex_vector:
    M1 = z*E + np.sum(A * np.exp(-hA*z), axis=2)

    M2 = z*E
    for i in range(len(hA)):
        M2 = M2 + A[:,:,i] * np.exp(-z*hA[i])
    
    max_error = np.max(np.abs(M1-M2))
    print(f"{z=}, {max_error=}")



z=(0.18768238909828594+0.5112431618245274j), max_error=8.881784197001252e-16
z=(0.2081850839606999+0.5313839497142626j), max_error=1.1102230246251565e-16
z=(0.4642926136276293+0.48576543947724693j), max_error=0.0
z=(0.41435159258727094+0.376082996638621j), max_error=1.7763568394002505e-15
z=(0.7756632928248347+0.7111295637249563j), max_error=2.220446049250313e-16
z=(0.20481136533587385+0.3654439581099752j), max_error=8.881784197001252e-16
z=(0.20476112264946933+0.30401387973619676j), max_error=8.881784197001252e-16
z=(0.28382145376642387+0.4360331828788847j), max_error=8.881784197001252e-16
z=(0.4555756991154081+0.600650300000408j), max_error=8.881784197001252e-16
z=(0.5727558564966749+0.8834419974529111j), max_error=8.881784197001252e-16


In [2]:
# Controller gradient computation
m,n,k = 3,4,6


tau_vector = np.array([i*0.1 for i in range(k)])
Kmask = np.random.rand(m,n,k) > 0.5
BKC = np.random.rand(m,n)


In [5]:
Kmask * tau_vector

array([[[0. , 0.1, 0.2, 0. , 0.4, 0. ],
        [0. , 0. , 0. , 0.3, 0.4, 0.5],
        [0. , 0. , 0.2, 0. , 0.4, 0.5],
        [0. , 0. , 0. , 0. , 0. , 0.5]],

       [[0. , 0.1, 0.2, 0.3, 0. , 0.5],
        [0. , 0. , 0.2, 0. , 0. , 0. ],
        [0. , 0.1, 0. , 0.3, 0.4, 0. ],
        [0. , 0.1, 0. , 0. , 0.4, 0.5]],

       [[0. , 0.1, 0. , 0.3, 0.4, 0.5],
        [0. , 0. , 0. , 0.3, 0. , 0.5],
        [0. , 0. , 0. , 0.3, 0.4, 0. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5]]])

In [19]:
result = (Kmask * tau_vector) * BKC[:,:,np.newaxis]
for i in range(result.shape[2]):
    error = result[:,:,i] - np.multiply(Kmask[:,:,i]*tau_vector[i], BKC)
    print(np.allclose(error, 0))

True
True
True
True
True
True


In [13]:
result[:,:,0]

array([[0.        , 0.        , 0.07739326, 0.35687544],
       [0.75113473, 0.2915329 , 0.35590233, 0.        ],
       [0.70750349, 0.18583073, 0.99316741, 0.        ]])

In [6]:
# Indexation of 3D arrays
n = 10
AA = []
for i in range(5):
    AA.append(
        (i+1) * np.eye(n)
    )

A=np.stack(AA, axis=2)

In [38]:
row_index = [0,2]
col_index = [0,1,2,3]
#row_index = np.array([0,2])
#col_index = np.array([0,1,2,3])
result = A[np.ix_(row_index, col_index, range(A.shape[2]))]



print(f"{result.shape}")
for k in range(result.shape[2]):
    print(result[:,:,k])

(2, 4, 5)
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[2. 0. 0. 0.]
 [0. 0. 2. 0.]]
[[3. 0. 0. 0.]
 [0. 0. 3. 0.]]
[[4. 0. 0. 0.]
 [0. 0. 4. 0.]]
[[5. 0. 0. 0.]
 [0. 0. 5. 0.]]


In [30]:
np.ix_(row_index, col_index, range(A.shape[2]))

(array([[[0]],
 
        [[1]],
 
        [[4]]]),
 array([[[0],
         [1],
         [2],
         [3]]]),
 array([[[0, 1, 2, 3, 4]]]))

In [ ]:
np.indices()

In [4]:
A = np.random.rand(4,4,10)

In [9]:
AA = A[:,:, [1,0,3]]

In [11]:
np.isclose(AA[:,:,0], A[:,:,1])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
np.concatenate([np.array([1,1,1]),np.array([]), np.array([2,2])], axis=0)

array([1., 1., 1., 2., 2.])

In [ ]:
# Comparison
A = np.stack([A0, A1, A1*10], axis=2) # (n_states, n_states, n_delays)
hA = hA=np.array([0, 1., 2, 3])

In [4]:
np.concatenate([A0[:,:,np.newaxis], A], axis=2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [5]:
DD = np.random.rand(3,3,4)
hDD = np.array([0.3, 0.46, 0.48, 1.5])
u = np.random.rand(3,) + 1j*np.random.rand(3,)
v = np.random.rand(3,) + 1j*np.random.rand(3,)

In [6]:
# one shot


In [7]:
DD.shape

(3, 3, 4)

In [8]:
np.conj(u[np.newaxis, ]) @ DD[:,:,0]

array([[0.9297204 -0.26193806j, 1.86890252-0.52321453j,
        1.74444528-0.5550986j ]])

In [9]:
np.ravel()

TypeError: ravel() missing 1 required positional argument: 'a'

In [64]:
pom = np.conj(u[np.newaxis, np.newaxis, ]) @ np.transpose(DD, (1,0,2))
pom

array([[[0.35420586-0.10532599j, 0.99196665-0.5031648j ,
         1.18214463-0.75940259j, 1.31047856-0.63000362j]],

       [[0.88901118-0.61335586j, 1.61633642-0.72388863j,
         0.88541662-0.57948834j, 1.06701478-0.38574745j]],

       [[0.73177854-0.37038361j, 0.73973774-0.48182061j,
         1.50150753-0.75744051j, 0.87277868-0.51356456j]]])

In [65]:
pom.shape

(3, 1, 4)

In [66]:
r = v[np.newaxis, :] @ np.transpose(pom, (1,0,2)) 

In [67]:
np.ravel(r).shape

(4,)

In [68]:
np.ravel(r)

array([1.93551363+0.56210115j, 3.41212929+1.17027306j,
       3.3489107 +1.3697247j , 3.01398257+1.45968292j])

In [69]:
np.conj(u[np.newaxis, ]) @ np.transpose(v[np.newaxis, :] @ DD, (1,0,2))

array([[[1.93551363+0.56210115j, 3.41212929+1.17027306j,
         3.3489107 +1.3697247j , 3.01398257+1.45968292j]]])

## Constructing nullspaces

In [12]:
E = np.eye(4)

In [13]:
E

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
uE = linalg.null_space(E.T)
vE = linalg.null_space(E)

In [16]:
uE

array([], shape=(4, 0), dtype=float64)

In [17]:
vE

array([], shape=(4, 0), dtype=float64)

In [18]:
uE.size

0

In [19]:
np.array([[[]]])

array([], shape=(1, 1, 0), dtype=float64)

In [21]:
np.empty(shape=(4,4,0))

array([], shape=(4, 4, 0), dtype=float64)

In [ ]:
np.empty_like()