In [1]:
import numpy as np

In [36]:
def theta_generator(n_opt: int, n_theta:int=10, is_real: bool=False):
    """ Generator for theta grid points in [0, 2*pi)^{m} """

    theta_grid = np.linspace(0, 2*np.pi, num=n_theta, endpoint=False)

    total = n_theta**n_opt

    id = np.zeros((n_opt,), dtype=int)
    theta = np.zeros((n_opt,), dtype=np.float64)

    endpoint = n_theta // 2 + 1 if is_real else n_theta # endpoint can be restricted for real matrices
    total = n_theta**n_opt if not is_real else (n_theta//2)**n_opt
    
    ix1, ix2 = 0, 0
    print(f"Total combinations: {total}, starting {theta=}, {endpoint=}")
    
    counter = 0
    while id[0] <= endpoint:
        # construct theta
        print(f"{id}")
        theta[-ix1-1] = theta_grid[ix2]
        print(f"Yielding theta: {theta}")
        # update indeces
        
        # form the next gridpoint
        id[-1] = id[-1] + 1
        j = len(id)
        while id[j-1] <= n_theta - 1:
            if j == 0:
                break
            id[j-1] = 0
            id[j-2] = id[j-2] + 1
            j = j - 1
    
        if counter > 10:
            break
        counter += 1

In [37]:
theta_generator(3, 5, is_real=False)

Total combinations: 125, starting theta=array([0., 0., 0.]), endpoint=5
[0 0 0]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]
[0 0 1]
Yielding theta: [0. 0. 0.]


In [ ]:
n_opt = 3
n_theta = 5
id = np.zeros((n_opt,), dtype=int)
theta_grid = np.linspace(0, 2*np.pi, num=n_theta, endpoint=False)
theta = np.zeros((n_opt,), dtype=np.float64)
endpoint = n_theta // 2 + 1 # not restricting to real matrices

while id[0] <= endpoint - 1:
    theta[:] = theta_grid[id]    
    # form the next gridpoint
    id[-1] = id[-1] + 1
    for j in range(n_opt-1, 0, -1):
        if id[j] < n_theta:
            break
        else:
            id[j] = 0
            id[j-1] += 1
        


theta=array([0., 0., 0.])
theta=array([0.        , 0.        , 1.25663706])
theta=array([0.        , 0.        , 2.51327412])
theta=array([0.        , 0.        , 3.76991118])
theta=array([0.        , 0.        , 5.02654825])
theta=array([0.        , 1.25663706, 0.        ])
theta=array([0.        , 1.25663706, 1.25663706])
theta=array([0.        , 1.25663706, 2.51327412])
theta=array([0.        , 1.25663706, 3.76991118])
theta=array([0.        , 1.25663706, 5.02654825])
theta=array([0.        , 2.51327412, 0.        ])
theta=array([0.        , 2.51327412, 1.25663706])
theta=array([0.        , 2.51327412, 2.51327412])
theta=array([0.        , 2.51327412, 3.76991118])
theta=array([0.        , 2.51327412, 5.02654825])
theta=array([0.        , 3.76991118, 0.        ])
theta=array([0.        , 3.76991118, 1.25663706])
theta=array([0.        , 3.76991118, 2.51327412])
theta=array([0.        , 3.76991118, 3.76991118])
theta=array([0.        , 3.76991118, 5.02654825])
theta=array([0.        ,